# version: '3'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 3000:3000
#     env_file:
#       - .env
#     volumes:
#       - .:/app

version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:8080'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules